version: '3'

services:

  mattermost:
    container_name: mattermost
    build:
      dockerfile: ./web/Dockerfile
      context: '.'
      args:
        MMDB_USER: mmuser
        MMDB_PASSWORD: mmuser_password
        MMDB_HOST: localhost
    image: mattermost:latest
    depends_on:
      - db
    network_mode: host

  nginx:
    container_name: nginx
    build:
      dockerfile: ./nginx/Dockerfile
      context: '.'
    image: mattermost-nginx:latest
    ports:
      - '80:80'
      - '443:443'
    network_mode: host

  db:
    container_name: mattermost-db
    image: postgres:alpine
    environment:
      - POSTGRES_USER=mmuser
      - POSTGRES_PASSWORD=mmuser_password
      - POSTGRES_DB=mattermost
    volumes:
      - 'mmdb:/var/lib/postgresql/data'
    network_mode: host
  
  mattermost-mail:
    container_name: mattermost-mail
    build:
      dockerfile: ./mailserver/Dockerfile
      context: '.'
    image: mattermost-mail:latest
    ports:
      - '10025:10025'
    depends_on:
      - mattermost
    network_mode: host

volumes:
  mmdb:
